!!python/object:argparse.Namespace
Experiment_name: ''
base_lr: 0.01
batch_size: 256
config: ./config/nturgbd-cross-view/test_bone.yaml
device: 0
eval_interval: 5
feeder: feeder.feeder
ignore_weights: []
log_interval: 100
model: null
model_args: {}
model_saved_name: ''
num_epoch: 80
num_worker: 32
only_train_epoch: 0
only_train_part: true
optimizer: SGD
phase: train
save_interval: 2
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 40
- 60
test_batch_size: 256
test_feeder_args: {}
train_feeder_args: {}
warm_up_epoch: 0
weight_decay: 0.0005
weights: null
work_dir: ./work_dir/temp
